name: Write Version to File
on:
  push:
    branches:
      - main

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
    - uses: actions/checkout@main
    - name: Update version
      uses: brettdorrans/write-version-to-file@main
      with:
        filename: '/.VERSION'
        placeholder: '${VERSION}'
